stages:
    - linter
    - test
    - coverage

linter:
    image: daedalusproject/base_bash_utils:latest
    stage: test
    script:
        - shellcheck lib/build_docker_image_functions.sh

unit_tests:
    image: daedalusproject/base_bash_utils:latest
    stage: test
    script:
        - make test

cover:
    image: daedalusproject/base_bash_utils:latest
    stage: coverage
    script:
        - make cover
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes
