stages:
    - linter
    - test
    - coverage
    - package

linter:
    image: daedalusproject/base_bash_utils:201904271450
    stage: test
    script:
        - shellcheck lib/build_docker_image_functions.sh

unit_tests:
    image: daedalusproject/base_bash_utils:201904271450
    stage: test
    script:
        - make test

cover:
    image: daedalusproject/base_bash_utils:201904271450
    stage: coverage
    script:
        - make cover
    coverage: /Coverage:\ (\d+\.\d+?)%$/
    artifacts:
        paths:
        - coverage
        expire_in: 15 minutes

create_deb_package:
    image: daedalusproject/base_deb_builder:201904271450
    stage: package
    before_script:
        - apt-get update
        - apt-get install -y shunit2
    script:
        - dpkg-buildpackage -uc -b
        - mkdir package
        - mv ../daedalus-project-docker-build*.deb package/
    artifacts:
        paths:
        - package
        expire_in: 15 minutes
